# Stage 1 : build frontend
FROM node:20 AS node-builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY resources/ resources/
RUN npm run build

# Stage 2 : backend Laravel
FROM php:8.2-fpm
RUN apt-get update && apt-get install -y git unzip libonig-dev libzip-dev zip curl \
    && docker-php-ext-install pdo pdo_pgsql mbstring zip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
WORKDIR /var/www/html
COPY . .
COPY --from=node-builder /app/dist public/

RUN composer install --optimize-autoloader --no-dev
RUN php artisan key:generate && php artisan storage:link

EXPOSE 9000
CMD ["php-fpm"]
